//
//  NotesDetailPresenter.swift
//  NoteManagerCleanSwift
//
//  Created by Lada Vrska on 19/10/2019.
//  Copyright (c) 2019 Lada Vrska. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NotesDetailPresentationLogic {
  func presentSomething(response: NotesDetail.FetchNote.Response)
}

class NotesDetailPresenter: NotesDetailPresentationLogic {
  weak var viewController: NotesDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: NotesDetail.FetchNote.Response) {
    let viewModel = NotesDetail.FetchNote.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
