//
//  NotesDetailInteractor.swift
//  NoteManagerCleanSwift
//
//  Created by Lada Vrska on 19/10/2019.
//  Copyright (c) 2019 Lada Vrska. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NotesDetailBusinessLogic {
  func fetchNote(request: NotesDetail.FetchNote.Request)
}

protocol NotesDetailDataStore {
  var note: Note? { get set }
}

class NotesDetailInteractor: NotesDetailBusinessLogic, NotesDetailDataStore {
  var presenter: NotesDetailPresentationLogic?
  var worker: NotesDetailWorker?
  var note: Note?
  
  // MARK: Do something
  
  func fetchNote(request: NotesDetail.FetchNote.Request) {
    worker = NotesDetailWorker()
    worker?.doSomeWork()
    
          //self.presenter?.showActivityIndicator()
//    notesWorker.fetchNotes {
//      print("$0: \($0)")
//      guard let notes = $0.value, $0.isSuccess else {
//        self.presenter?.presentFetchedNotes(error: $0.error as? NotesStoreError ?? .cannotFetch("Cannot fetch notes"))
//        return
//      }
//      self.notes = notes as? [Note] ?? []
//      print("notes: \(notes)")
//          //self.presenter?.hideActivityIndicator()
//      self.presenter?.presentFetchedNotes(response: NotesListModels.FetchNotes.Response(notes: notes))
//    }
    
    let response = NotesDetail.FetchNote.Response()
    presenter?.presentSomething(response: response)
  }
}
