//
//  NotesDetailViewController.swift
//  NoteManagerCleanSwift
//
//  Created by Lada Vrska on 19/10/2019.
//  Copyright (c) 2019 Lada Vrska. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NotesDetailDisplayLogic: class {
  func displaySomething(viewModel: NotesDetail.Something.ViewModel)
}

class NotesDetailViewController: UIViewController, NotesDetailDisplayLogic {
  var interactor: NotesDetailBusinessLogic?
  var router: (NSObjectProtocol & NotesDetailRoutingLogic & NotesDetailDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup() {
    let viewController = self
    let interactor = NotesDetailInteractor()
    let presenter = NotesDetailPresenter()
    let router = NotesDetailRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad() {
    super.viewDidLoad()
    doSomething()
    let myNote = self.router?.dataStore?.note
    print("Notes detail note: \(String(describing: myNote))")
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething() {
    let request = NotesDetail.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: NotesDetail.Something.ViewModel) {
    //nameTextField.text = viewModel.name
  }
}
